#!/bin/bash

#	PciIds web database
#	Copyright (C) 2008 Michal Vaner (vorner@ucw.cz)
#
#	This program is free software; you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	he Free Software Foundation; either version 2 of the License, or
#	(at your option) any later version.
#
#	This program is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with this program; if not, write to the Free Software
#	Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

set -e

cp perl/cf/head.ids pci.ids.new
./perl/scripts/export.pl PC >> pci.ids.new
cat perl/cf/class_head.ids >> pci.ids.new
./perl/scripts/export.pl PD >> pci.ids.new
if ! [ -f docs/pci.ids ] || ! cmp static/pci.ids pci.ids.new >/dev/null ; then
	ln pci.ids.new ~/origs/00-current
	ln pci.ids.new docs/pci.ids
	bzip2 -9c <docs/pci.ids >docs/pci.ids.bz2
	gzip -9c <docs/pci.ids >docs/pci.ids.gz
fi

rm pci.ids.new
