#!/bin/bash

#	PciIds web database
#	Copyright (C) 2008 Michal Vaner (vorner@ucw.cz)
#
#	This program is free software; you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	he Free Software Foundation; either version 2 of the License, or
#	(at your option) any later version.
#
#	This program is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with this program; if not, write to the Free Software
#	Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

set -e

#cd perl
touch usb.ids.new
nodes="UD UC AT HD UR BS PH HT UL HC VT"
for node in $nodes; do
    if [ -e cf/header_$node.ids ]; then
	cat cf/header_$node.ids >> usb.ids.new
    fi
    ./scripts/export.pl $node >> usb.ids.new
done
#cd ..
if ! [ -f usb.ids.nohead ] || ! cmp usb.ids.nohead usb.ids.new >/dev/null ; then
	VERSION=`date '+%Y.%m.%d'`
	DATE=`date '+%F %T'`
	sed <cf/head.ids >usb.ids.final -e "s/@VERSION@/$VERSION/;s/@DATE@/$DATE/"
	cat usb.ids.new >> usb.ids.final

	ln -f usb.ids.final usb.ids
	ln -f usb.ids.new usb.ids.nohead
	rm usb.ids.final

	bzip2 -9c <usb.ids >usb.ids.bz2.new
	mv usb.ids.bz2.new usb.ids.bz2

	gzip -9c <usb.ids >usb.ids.gz.new
	mv usb.ids.gz.new usb.ids.gz
fi

rm usb.ids.new
